### ISSUE TITLE
[Request]: Can you make a website for me?

### ISSUE THREAD

**Issue by ajskateboarder** [jdev082/hosting#1]
### Link to service

Code is linked in this issue

### How many resources does it use?

Not much. Use the below file and host it on thanks.jdev.eu.org

```html
<html><head><title>thanks jdev :333</title></head><body>Thanks to jdev for hosting this. Jdev is so amazing. Without this service, I couldn't host this one-liner html file. Also first!!! <small>@ajskateboarder</small></body></html>
```

### Database

No

### I have read the requirements.

- [X] I have read the requirements.

**Comment by jdev082** [comment]
Your request and software will be analyzed at this time. Shortly, you will receive a yes or no answer as well as reasoning.

**Comment by jdev082** [comment]
@lemystic I'd prefer if you just made it a normal web page instead of something that doesn't need to be a server.

**Comment by ajskateboarder** [comment]
I updated the issue. Would it still be hosted under your domain?

**Comment by jdev082** [comment]
> I updated the issue. Would it still be hosted under your domain?

My hosting service is rather new so not everything has been decided yet. I have decided where pages are going to go.

**https://jdev.eu.org/pages/username**

I would also prefer if you had the site hosted in a public github repo so I can just clone it into the directory.

**Comment by ajskateboarder** [comment]
Okay, never mind this request then
